[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''discount_percent = 0,'''
position = 'after'
payload = '''
daisy_discount = 1,
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''self.cost = math.max(1, math.floor((self.base_cost + self.extra_cost + 0.5)*(100-G.GAME.discount_percent)/100))'''
position = 'after'
payload = '''self.cost = self.cost / G.GAME.daisy_discount'''
match_indent = true


